language: node_js
node_js:
    - "4.2.6"
install:
    - npm install
    - npm install -g codecov
script:
    - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
    - codecov
before_script:
    - npm run lint
